---
default_locale: zh_CN
title: 华人新站
site_description: 大家的，自由的，没有广告的社区
short_site_description: 有史以来最友好的社区
contact_email: admin@chinese1.net
contact_url: https://bbs.chinese1.com/contact.html
notification_email: noreply@bbs.chinese1.com
site_contact_username: system
logo: "/uploads/default/original/1X/b5a33c454281131f8b2526021245ad8d3cce1ca7.gif"
logo_small: "/uploads/default/original/1X/54c28cb20f96392d065e1f690bd2d20e17bac4f2.gif"
digest_logo: "/uploads/default/original/1X/b5a33c454281131f8b2526021245ad8d3cce1ca7.gif"
mobile_logo: "/uploads/default/original/1X/a691a970345b63055d271d8565fd1505a9bb5711.png"
logo_dark: "/uploads/default/original/1X/a691a970345b63055d271d8565fd1505a9bb5711.png"
large_icon: "/uploads/default/original/1X/54c28cb20f96392d065e1f690bd2d20e17bac4f2.gif"
top_menu: categories|latest|new|unread|top
desktop_category_page_style: categories_boxes_with_topics
relative_date_duration: '1'
fixed_category_positions: 'true'
fixed_category_positions_on_create: 'true'
username_change_period: '0'
email_editable: 'false'
allow_uncategorized_topics: 'false'
emoji_set: apple
default_trust_level: '1'
trusted_users_can_edit_others: 'false'
default_email_digest_frequency: '1440'
default_other_external_links_in_new_tab: 'true'
tagging_enabled: 'true'
tag_style: bullet
max_tags_per_topic: '3'
min_trust_to_create_tag: admin
show_filter_by_tag: 'true'
